from flask import Flask, render_template, request, redirect
import json
from datetime import date

app = Flask(__name__)
DATA_FILE = "workers_data.json"

def load_data():
    with open(DATA_FILE, "r", encoding="utf-8") as f:
            return json.load(f)

            def save_data(data):
                with open(DATA_FILE, "w", encoding="utf-8") as f:
                        json.dump(data, f, indent=2)

                        @app.route("/", methods=["GET", "POST"])
                        def index():
                            worker = None
                                final_text = None

                                    if request.method == "POST":
                                            qid = request.form.get("qid")
                                                    data = load_data()

                                                            if qid in data:
                                                                        worker = data[qid]

                                                                                    # make sure attendance exists
                                                                                                worker.setdefault("attendance", {"daily": {}, "leave": {"from":"","to":"","reason":""}})

                                                                                                            text = worker.get("docText", "")
                                                                                                                        for k, v in worker.items():
                                                                                                                                        if isinstance(v, str):
                                                                                                                                                            text = text.replace("{{"+k+"}}", v)

                                                                                                                                                                        final_text = text
                                                                                                                                                                                else:
                                                                                                                                                                                            worker = {"error": "QID not found"}
                                                                                                                                                                                                        worker.setdefault("extra", {})

                                                                                                                                                                                                            return render_template("index.html", worker=worker, final_text=final_text)
                                                                                                                                                                                                            @app.route("/save", methods=["POST"])
                                                                                                                                                                                                            def save():
                                                                                                                                                                                                                data = load_data()
                                                                                                                                                                                                                    qid = request.form["qid"]

                                                                                                                                                                                                                        old = data.get(qid, {})
                                                                                                                                                                                                                            extra = old.get("extra", {})

                                                                                                                                                                                                                                key = request.form.get("extra_key")
                                                                                                                                                                                                                                    value = request.form.get("extra_value")
                                                                                                                                                                                                                                        if key and value:
                                                                                                                                                                                                                                                extra[key] = value

                                                                                                                                                                                                                                                    data[qid] = {
                                                                                                                                                                                                                                                            **old,
                                                                                                                                                                                                                                                                    "name": request.form.get("name", old.get("name","")),
                                                                                                                                                                                                                                                                            "trade": request.form.get("trade", old.get("trade","")),
                                                                                                                                                                                                                                                                                    "qid": qid,
                                                                                                                                                                                                                                                                                            "passport": request.form.get("passport", old.get("passport","")),
                                                                                                                                                                                                                                                                                                    "mobile_no": request.form.get("mobile_no", old.get("mobile_no","")),
                                                                                                                                                                                                                                                                                                            "salary": request.form.get("salary", old.get("salary","")),
                                                                                                                                                                                                                                                                                                                    "food": request.form.get("food", old.get("food","")),
                                                                                                                                                                                                                                                                                                                            "camp": request.form.get("camp", old.get("camp","")),
                                                                                                                                                                                                                                                                                                                                    "offerDate": request.form.get("offerDate", old.get("offerDate","")),
                                                                                                                                                                                                                                                                                                                                            "docText": request.form.get("docText", old.get("docText","")),
                                                                                                                                                                                                                                                                                                                                                    "attendance": old.get("attendance", {"daily": {}, "leave": {"from":"","to":"","reason":""}}),
                                                                                                                                                                                                                                                                                                                                                            "extra": extra
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                    save_data(data)
                                                                                                                                                                                                                                                                                                                                                                        return redirect("/")

                                                                                                                                                                                                                                                                                                                                                                        @app.route("/attendance", methods=["POST"])
                                                                                                                                                                                                                                                                                                                                                                        def attendance():
                                                                                                                                                                                                                                                                                                                                                                            data = load_data()
                                                                                                                                                                                                                                                                                                                                                                                qid = request.form.get("qid")
                                                                                                                                                                                                                                                                                                                                                                                    status = request.form.get("status")
                                                                                                                                                                                                                                                                                                                                                                                        today = str(date.today())

                                                                                                                                                                                                                                                                                                                                                                                            if qid in data:
                                                                                                                                                                                                                                                                                                                                                                                                    data[qid].setdefault("attendance", {"daily": {}, "leave": {"from":"","to":"","reason":""}})

                                                                                                                                                                                                                                                                                                                                                                                                            if status == "leave":
                                                                                                                                                                                                                                                                                                                                                                                                                        data[qid]["attendance"]["leave"] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                        "from": request.form.get("leave_from",""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "to": request.form.get("leave_to",""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "reason": request.form.get("leave_reason","")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data[qid]["attendance"]["daily"][today] = status

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                save_data(data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return redirect("/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route("/add_extra", methods=["POST"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def add_extra():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data = load_data()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            qid = request.form.get("qid")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key = request.form.get("extra_key")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value = request.form.get("extra_value")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("FORM:", request.form)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("QID:", qid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("KEY:", key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("VALUE:", value)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if qid in data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if "extra" not in data[qid]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data[qid]["extra"] = {}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data[qid]["extra"][key] = value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            save_data(data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect("/")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.run(debug=True)